[build]
   base = "."
   publish = "dist/"
   environment = { NODE_VERSION = "22.7.0", NPM_VERSION = "10.8.3" }

[context.production]
   environment = {BASE_URL = "https://build.thiss.io/", MDQ_URL = "https://md.thiss.io/entities/", SEARCH_URL = "https://md.thiss.io/entities" }
   command = "make netlify"

[context.staging]
   environment = {BASE_URL = "https://staging.build.thiss.io/", MDQ_URL = "https://md-staging.thiss.io/entities/", SEARCH_URL = "https://md-staging.thiss.io/entities" }
   command = "make netlify"

[context.deploy-preview]
   environment = { MDQ_URL = "https://md-dev.thiss.io/entities/", SEARCH_URL = "https://md-dev.thiss.io/entities" }
   command = "make netlify"

[context.branch-deploy]
   environment = { MDQ_URL = "https://md-staging.thiss.io/entities/", SEARCH_URL = "https://md-staging.thiss.io/entities" }
   command = "make netlify"
